server:
  port:8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currencyExchange
    userName: postgres
    password: 123
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect